In [ ]:
# Bismillah

In [10]:
import numpy as np
import pandas as pd
import datetime as dt
!pip install pandas_datareader
from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('precision', 7)
from pandas_datareader import data as web

Requirement already satisfied: pandas_datareader in /home/ibrar/anaconda3/lib/python3.9/site-packages (0.10.0)
Requirement already satisfied: lxml in /home/ibrar/anaconda3/lib/python3.9/site-packages (from pandas_datareader) (4.6.3)
Requirement already satisfied: pandas>=0.23 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from pandas_datareader) (1.3.4)
Requirement already satisfied: requests>=2.19.0 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from pandas_datareader) (2.26.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->pandas_datareader) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->pandas_datareader) (1.20.3)
Requirement already satisfied: idna<4,>=2.5 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (1.25.11)
Requirement already satisfied: six>=1.5 in /home/ibrar/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas_datareader) (1.16.0)

In [11]:
msft = web.DataReader('MSFT', 'yahoo', '2012-01-01', '2013-12-30')
msft

# collects the data from yahoo finance for Microsoft for the said period and stores it in data frame, msft.

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6231327
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1320114
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.3581734
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7055035
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4066372
...,...,...,...,...,...,...
2013-12-23,36.8899994,36.5499992,36.8100014,36.6199989,25128700.0,31.3362408
2013-12-24,37.1699982,36.6399994,36.7200012,37.0800018,14243000.0,31.7298584
2013-12-26,37.4900017,37.1699982,37.2000008,37.4399986,17612800.0,32.0379295
2013-12-27,37.6199989,37.1699982,37.5800018,37.2900009,14563000.0,31.9095783
2013-12-30,37.3800011,36.9000015,37.2200012,37.2900009,16290500.0,31.9095783

### Shifting and lagging time-series data:

In [9]:
msftAC = msft['Adj Close']
msftAC

# select only 'Adj Close' column from the msft data frame, and store it in a series, msftAC.

Date
2012-01-03    21.6231327
2012-01-04    22.1320133
2012-01-05    22.3581753
2012-01-06    22.7055073
2012-01-09    22.4066410
                 ...
2013-12-23    31.3362350
2013-12-24    31.7298565
2013-12-26    32.0379181
2013-12-27    31.9095726
2013-12-30    31.9095726
Name: Adj Close, Length: 501, dtype: float64

In [10]:
type(msftAC)

# msftAC is a series. We can convert it to a data frame by typing: msftAC = msft[['Adj Close']]

pandas.core.series.Series

In [11]:
shift_forward = msftAC.shift(1)
msftAC.head(), shift_forward.head()
# This will shift the prices one day forward.
# results in one NaN value at the start since there was no value prior to be shifted to 2012-01-03.
# the number of NaN values will depend on the number of indices we are shifting forward or backward. For instance, the index is 
# daily dates, so if we shift one day forward, it means we are forwarding one index resulting into one NaN value. If we would 
# shift 2 days forward, it means we are forwarding two indices resulting into two NaN values.

(Date
 2012-01-03    21.6231327
 2012-01-04    22.1320133
 2012-01-05    22.3581753
 2012-01-06    22.7055073
 2012-01-09    22.4066410
 Name: Adj Close, dtype: float64,
 Date
 2012-01-03           NaN
 2012-01-04    21.6231327
 2012-01-05    22.1320133
 2012-01-06    22.3581753
 2012-01-09    22.7055073
 Name: Adj Close, dtype: float64)

In [12]:
msftAC.tail(), shift_forward.tail()
# the last price 31.9755402 on date 2013-12-30 in msftAC has been lost away in shift_forward since there is no index available for
# it now after the prices have been shifted one day forward. So, we got one NaN value at the start and one value lost at the end
# by shifting one day forward.

(Date
 2013-12-23    31.3362350
 2013-12-24    31.7298565
 2013-12-26    32.0379181
 2013-12-27    31.9095726
 2013-12-30    31.9095726
 Name: Adj Close, dtype: float64,
 Date
 2013-12-23    31.4902611
 2013-12-24    31.3362350
 2013-12-26    31.7298565
 2013-12-27    32.0379181
 2013-12-30    31.9095726
 Name: Adj Close, dtype: float64)

In [13]:
shift_backward = msftAC.shift(-2)
# will shift two days (two indices) backward.

In [14]:
msftAC, shift_backward
# inserts two NaNs at the end since we have shifted two days (two indices) backward and the first two values lost since there are 
# no indices available for them.

(Date
 2012-01-03    21.6231327
 2012-01-04    22.1320133
 2012-01-05    22.3581753
 2012-01-06    22.7055073
 2012-01-09    22.4066410
                  ...
 2013-12-23    31.3362350
 2013-12-24    31.7298565
 2013-12-26    32.0379181
 2013-12-27    31.9095726
 2013-12-30    31.9095726
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03    22.3581753
 2012-01-04    22.7055073
 2012-01-05    22.4066410
 2012-01-06    22.4874115
 2012-01-09    22.3904819
                  ...
 2013-12-23    32.0379181
 2013-12-24    31.9095726
 2013-12-26    31.9095726
 2013-12-27           NaN
 2013-12-30           NaN
 Name: Adj Close, Length: 501, dtype: float64)

In [15]:
shift_1sec = msftAC.shift(1, freq = 'S')

In [16]:
msftAC, shift_1sec
# the prices have been shifted just one second forward each day. That means that the prices still exist on the same date. So, no
# value is lost and no NaN is inserted.
# the frequency could be changed to any desirable level such as hour etc.
# Note that the index labels have been adjusted according to the specified frequency resulting into a new dataframe or series in 
# this case.

(Date
 2012-01-03    21.6231327
 2012-01-04    22.1320133
 2012-01-05    22.3581753
 2012-01-06    22.7055073
 2012-01-09    22.4066410
                  ...
 2013-12-23    31.3362350
 2013-12-24    31.7298565
 2013-12-26    32.0379181
 2013-12-27    31.9095726
 2013-12-30    31.9095726
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03 00:00:01    21.6231327
 2012-01-04 00:00:01    22.1320133
 2012-01-05 00:00:01    22.3581753
 2012-01-06 00:00:01    22.7055073
 2012-01-09 00:00:01    22.4066410
                           ...
 2013-12-23 00:00:01    31.3362350
 2013-12-24 00:00:01    31.7298565
 2013-12-26 00:00:01    32.0379181
 2013-12-27 00:00:01    31.9095726
 2013-12-30 00:00:01    31.9095726
 Name: Adj Close, Length: 501, dtype: float64)

In [17]:
shift_1sec['2012-01-03':'2012-01-06']
# note that the indices now include the time as well in addition to the date.

Date
2012-01-03 00:00:01    21.6231327
2012-01-04 00:00:01    22.1320133
2012-01-05 00:00:01    22.3581753
2012-01-06 00:00:01    22.7055073
Name: Adj Close, dtype: float64

### Practical Example:

In [18]:
msftAC, msftAC.shift(1)
# the prices have been shifted one day forward.

(Date
 2012-01-03    21.6231327
 2012-01-04    22.1320133
 2012-01-05    22.3581753
 2012-01-06    22.7055073
 2012-01-09    22.4066410
                  ...
 2013-12-23    31.3362350
 2013-12-24    31.7298565
 2013-12-26    32.0379181
 2013-12-27    31.9095726
 2013-12-30    31.9095726
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03           NaN
 2012-01-04    21.6231327
 2012-01-05    22.1320133
 2012-01-06    22.3581753
 2012-01-09    22.7055073
                  ...
 2013-12-23    31.4902611
 2013-12-24    31.3362350
 2013-12-26    31.7298565
 2013-12-27    32.0379181
 2013-12-30    31.9095726
 Name: Adj Close, Length: 501, dtype: float64)

In [19]:
msftAC/msftAC

Date
2012-01-03    1.0
2012-01-04    1.0
2012-01-05    1.0
2012-01-06    1.0
2012-01-09    1.0
             ...
2013-12-23    1.0
2013-12-24    1.0
2013-12-26    1.0
2013-12-27    1.0
2013-12-30    1.0
Name: Adj Close, Length: 501, dtype: float64

In [20]:
msftAC / msftAC.shift(1)
# the dividsion is based on the same index labels. That is, the price on 2012-01-04 in msftAC is divided the price on 2012-01-04 in
# msftAC.shift(1). This is equal t`o (current price divided by previous price). The previous price is the amount invested.

# Interpretation: the $1 invested has grown to $1.0235337. So, the net return is $1.0235337 - 1 = $0.0235337. That is why we need
# to subtract 1 as shown below.
# the first value is NaN because value is missing in msftAC.shift(1) on 2012-01-03.
# the last value is 1.00000 because in both msftAC and msftAC.shift(1) the value on 2013-12-30 is the same.

# Very important to note that we CANNOT say that $1 investment at the start (2012-01-03) has grown to (or in this case 
# has remained same) to $1 at the end of the period (2013-12-30) since we can see that the adj close price at the start
# is $21.62 and at the end is $31.90. So, there is definately a gain. But then why we have 1 at the end of the output of
# this cell? It is because these returns are computed on daily basis. So, this 1 shows that $1 dollar invested on 2013-12
#-27 has remained same $1 and it makes sense since the price has remained unchanged from 2013-12-27 to 2013-12-30. To find
# the total return, we need to find the cumulative product.

Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0102188
2012-01-06    1.0155349
2012-01-09    0.9868373
                ...
2013-12-23    0.9951088
2013-12-24    1.0125612
2013-12-26    1.0097089
2013-12-27    0.9959940
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [21]:
np.cumprod(msftAC / msftAC.shift(1))

# just for the confirmation of the above.

Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0339933
2012-01-06    1.0500563
2012-01-09    1.0362347
                ...
2013-12-23    1.4491996
2013-12-24    1.4674033
2013-12-26    1.4816502
2013-12-27    1.4757146
2013-12-30    1.4757146
Name: Adj Close, Length: 501, dtype: float64

In [22]:
31.9095650 / 21.6231346

# just for the confirmation above

1.4757141177856794

In [23]:
percent_change = msftAC / msftAC.shift(1) - 1
percent_change
# gives the net daily change or return.
# the price has increased by 2.3% from 2012-01-03 to 2012-01-04.

Date
2012-01-03          NaN
2012-01-04    0.0235341
2012-01-05    0.0102188
2012-01-06    0.0155349
2012-01-09   -0.0131627
                ...
2013-12-23   -0.0048912
2013-12-24    0.0125612
2013-12-26    0.0097089
2013-12-27   -0.0040060
2013-12-30    0.0000000
Name: Adj Close, Length: 501, dtype: float64

### Frequency Conversion of Time-Series Data:

In [24]:
sample = msftAC[:2]
sample
# selected first 2 rows and stored them in 'sample'

Date
2012-01-03    21.6231327
2012-01-04    22.1320133
Name: Adj Close, dtype: float64

In [25]:
sample.asfreq('H')
# to have hourly data between the two index labels.
# a new index with hourly index labels has been created by pandas, but when aligning to the original time series, only two values
# were found, thereby leaving the others filled with NaN. This default behaviour can be changed as follows:

Date
2012-01-03 00:00:00    21.6231327
2012-01-03 01:00:00           NaN
2012-01-03 02:00:00           NaN
2012-01-03 03:00:00           NaN
2012-01-03 04:00:00           NaN
2012-01-03 05:00:00           NaN
2012-01-03 06:00:00           NaN
2012-01-03 07:00:00           NaN
2012-01-03 08:00:00           NaN
2012-01-03 09:00:00           NaN
2012-01-03 10:00:00           NaN
2012-01-03 11:00:00           NaN
2012-01-03 12:00:00           NaN
2012-01-03 13:00:00           NaN
2012-01-03 14:00:00           NaN
2012-01-03 15:00:00           NaN
2012-01-03 16:00:00           NaN
2012-01-03 17:00:00           NaN
2012-01-03 18:00:00           NaN
2012-01-03 19:00:00           NaN
2012-01-03 20:00:00           NaN
2012-01-03 21:00:00           NaN
2012-01-03 22:00:00           NaN
2012-01-03 23:00:00           NaN
2012-01-04 00:00:00    22.1320133
Freq: H, Name: Adj Close, dtype: float64

In [26]:
sample.asfreq('H', method = 'ffill')
# forward fill will take the earlier known value and fill all the missing values with it.

Date
2012-01-03 00:00:00    21.6231327
2012-01-03 01:00:00    21.6231327
2012-01-03 02:00:00    21.6231327
2012-01-03 03:00:00    21.6231327
2012-01-03 04:00:00    21.6231327
2012-01-03 05:00:00    21.6231327
2012-01-03 06:00:00    21.6231327
2012-01-03 07:00:00    21.6231327
2012-01-03 08:00:00    21.6231327
2012-01-03 09:00:00    21.6231327
2012-01-03 10:00:00    21.6231327
2012-01-03 11:00:00    21.6231327
2012-01-03 12:00:00    21.6231327
2012-01-03 13:00:00    21.6231327
2012-01-03 14:00:00    21.6231327
2012-01-03 15:00:00    21.6231327
2012-01-03 16:00:00    21.6231327
2012-01-03 17:00:00    21.6231327
2012-01-03 18:00:00    21.6231327
2012-01-03 19:00:00    21.6231327
2012-01-03 20:00:00    21.6231327
2012-01-03 21:00:00    21.6231327
2012-01-03 22:00:00    21.6231327
2012-01-03 23:00:00    21.6231327
2012-01-04 00:00:00    22.1320133
Freq: H, Name: Adj Close, dtype: float64

In [27]:
sample.asfreq('H', method = 'bfill')
# backward fill will take the next known value and fill the missing values in the backward direction.

Date
2012-01-03 00:00:00    21.6231327
2012-01-03 01:00:00    22.1320133
2012-01-03 02:00:00    22.1320133
2012-01-03 03:00:00    22.1320133
2012-01-03 04:00:00    22.1320133
2012-01-03 05:00:00    22.1320133
2012-01-03 06:00:00    22.1320133
2012-01-03 07:00:00    22.1320133
2012-01-03 08:00:00    22.1320133
2012-01-03 09:00:00    22.1320133
2012-01-03 10:00:00    22.1320133
2012-01-03 11:00:00    22.1320133
2012-01-03 12:00:00    22.1320133
2012-01-03 13:00:00    22.1320133
2012-01-03 14:00:00    22.1320133
2012-01-03 15:00:00    22.1320133
2012-01-03 16:00:00    22.1320133
2012-01-03 17:00:00    22.1320133
2012-01-03 18:00:00    22.1320133
2012-01-03 19:00:00    22.1320133
2012-01-03 20:00:00    22.1320133
2012-01-03 21:00:00    22.1320133
2012-01-03 22:00:00    22.1320133
2012-01-03 23:00:00    22.1320133
2012-01-04 00:00:00    22.1320133
Freq: H, Name: Adj Close, dtype: float64

### Resampling of time-series:

In [28]:
msftAC / msftAC.shift()
# I haven't confirmed it but i think the default argument for shift is 1 which means to shift prices forward by one day.

Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0102188
2012-01-06    1.0155349
2012-01-09    0.9868373
                ...
2013-12-23    0.9951088
2013-12-24    1.0125612
2013-12-26    1.0097089
2013-12-27    0.9959940
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [29]:
(1 + (msftAC / msftAC.shift() - 1))
# this and immediately above seems to produce the same result. Plus1 and minus1 cancels out so the result is the same as immediately above.

Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0102188
2012-01-06    1.0155349
2012-01-09    0.9868373
                ...
2013-12-23    0.9951088
2013-12-24    1.0125612
2013-12-26    1.0097089
2013-12-27    0.9959940
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [30]:
msft_cum_ret = (1 + (msftAC / msftAC.shift() - 1)).cumprod()
msft_cum_ret
# cumprod stands for cummulative product.
# it multiplies the value on 2012-01-04 with the value on 2012-01-05 and produces the product in the index label 2012-01-05. This product 
# can be called cumulative daily return.
# $1 dollar invested on 2012-01-03 has grown to $1.475 on 2013-12-30.

Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0339933
2012-01-06    1.0500563
2012-01-09    1.0362347
                ...
2013-12-23    1.4491996
2013-12-24    1.4674033
2013-12-26    1.4816502
2013-12-27    1.4757146
2013-12-30    1.4757146
Name: Adj Close, Length: 501, dtype: float64

In [31]:
msft_cum_ret['1/1/2012':'1/31/2012']
# note that typing the date in this pattern is the same as typing 2012-01-04 and so on.
# this gives us daily cumulative returns for all the month as explained above.

Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0339933
2012-01-06    1.0500563
2012-01-09    1.0362347
2012-01-10    1.0399701
2012-01-11    1.0354874
2012-01-12    1.0459471
2012-01-13    1.0552859
2012-01-17    1.0556594
2012-01-18    1.0545387
2012-01-19    1.0504297
2012-01-20    1.1098244
2012-01-23    1.1105717
2012-01-24    1.0960032
2012-01-25    1.1042211
2012-01-26    1.1019801
2012-01-27    1.0918939
2012-01-30    1.1060890
2012-01-31    1.1031005
Name: Adj Close, dtype: float64

In [32]:
msft_cum_ret['1/1/2012':'1/31/2012'].mean()
# mean cumulative return of January 2012. It is a mean of all the daily cumulative returns in January.
# to calculate each month mean cumulative return, we have to write this command 24 times for all 24 months.

1.0686747794135787

In [33]:
msft_cum_ret['1/2012'].mean()
# an alternative to the above method to compute monthly mean.

1.0686747794135787

In [34]:
(msftAC/msftAC.shift()).mean() # mean of daily returns.

1.0008829546895484

In [35]:
msft_cum_ret

Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0339933
2012-01-06    1.0500563
2012-01-09    1.0362347
                ...
2013-12-23    1.4491996
2013-12-24    1.4674033
2013-12-26    1.4816502
2013-12-27    1.4757146
2013-12-30    1.4757146
Name: Adj Close, Length: 501, dtype: float64

In [36]:
msft_monthly_cum_ret = msft_cum_ret.resample("M")
msft_monthly_cum_ret
# a better and efficient alternative to the above two methods to compute monthly means.
# does not return a dataframe any longer but an object stored at some location in memory. Nevermind, all the aggregation and interpolation
# can still be validly performed as shown below.

In [37]:
def print_info(groupobject):
    for i, k in groupobject:
        print (i)
        print (k)

In [38]:
print_info(msft_monthly_cum_ret)
# the daily cumulative returns have been grouped by month. In total, we will have 24 groups since we have 24 months.

2012-01-31 00:00:00
Date
2012-01-03          NaN
2012-01-04    1.0235341
2012-01-05    1.0339933
2012-01-06    1.0500563
2012-01-09    1.0362347
2012-01-10    1.0399701
2012-01-11    1.0354874
2012-01-12    1.0459471
2012-01-13    1.0552859
2012-01-17    1.0556594
2012-01-18    1.0545387
2012-01-19    1.0504297
2012-01-20    1.1098244
2012-01-23    1.1105717
2012-01-24    1.0960032
2012-01-25    1.1042211
2012-01-26    1.1019801
2012-01-27    1.0918939
2012-01-30    1.1060890
2012-01-31    1.1031005
Name: Adj Close, dtype: float64
2012-02-29 00:00:00
Date
2012-02-01    1.1165484
2012-02-02    1.1187899
2012-02-03    1.1296231
2012-02-06    1.1281287
2012-02-07    1.1337319
2012-02-08    1.1453119
2012-02-09    1.1494213
2012-02-10    1.1393352
2012-02-13    1.1423238
2012-02-14    1.1374356
2012-02-15    1.1299154
2012-02-16    1.1765409
2012-02-17    1.1750367
2012-02-21    1.1821809
2012-02-22    1.1757888
2012-02-23    1.1795487
2012-02-24    1.1836848
2012-02-27    1.1787968
2012-02-28    1.1983496
2012-02-29    1.1934613
Name: Adj Close, dtype: float64
2012-03-31 00:00:00
Date
2012-03-01    1.2141415
2012-03-02    1.2062456
2012-03-05    1.1957171
2012-03-06    1.1866929
2012-03-07    1.1972214
2012-03-08    1.2036136
2012-03-09    1.2028614
2012-03-12    1.2047418
2012-03-13    1.2284305
2012-03-14    1.2321907
2012-03-15    1.2351985
2012-03-16    1.2257979
2012-03-19    1.2107578
2012-03-20    1.2028614
2012-03-21    1.1998534
2012-03-22    1.2032375
2012-03-23    1.2036136
2012-03-26    1.2254224
2012-03-27    1.2227899
2012-03-28    1.2103818
2012-03-29    1.2077497
2012-03-30    1.2130139
Name: Adj Close, dtype: float64
2012-04-30 00:00:00
Date
2012-04-02    1.2141415
2012-04-03    1.2009813
2012-04-04    1.1735326
2012-04-05    1.1851890
2012-04-09    1.1693964
2012-04-10    1.1457078
2012-04-11    1.1411955
2012-04-12    1.1648840
2012-04-13    1.1584922
2012-04-16    1.1686445
2012-04-17    1.1821809
2012-04-18    1.1709002
2012-04-19    1.1660122
2012-04-20    1.2190300
2012-04-23    1.2077497
2012-04-24    1.2002294
2012-04-25    1.2107578
2012-04-26    1.2073737
2012-04-27    1.2024853
2012-04-30    1.2039894
Name: Adj Close, dtype: float64
2012-05-31 00:00:00
Date
2012-05-01    1.2036136
2012-05-02    1.1957171
2012-05-03    1.1942133
2012-05-04    1.1648840
2012-05-07    1.1524759
2012-05-08    1.1468356
2012-05-09    1.1566121
2012-05-10    1.1558601
2012-05-11    1.1716526
2012-05-14    1.1536041
2012-05-15    1.1433849
2012-05-16    1.1316521
2012-05-17    1.1248398
2012-05-18    1.1078082
2012-05-21    1.1259750
2012-05-22    1.1263534
2012-05-23    1.1017525
2012-05-24    1.1002385
2012-05-25    1.0998598
2012-05-29    1.1187836
2012-05-30    1.1104575
2012-05-31    1.1047803
Name: Adj Close, dtype: float64
2012-06-30 00:00:00
Date
2012-06-01    1.0767729
2012-06-04    1.0805578
2012-06-05    1.0790437
2012-06-06    1.1108357
2012-06-07    1.1062937
2012-06-08    1.1221904
2012-06-11    1.0938042
2012-06-12    1.1085650
2012-06-13    1.1025088
2012-06-14    1.1104575
2012-06-15    1.1361939
2012-06-18    1.1293813
2012-06-19    1.1619308
2012-06-20    1.1706356
2012-06-21    1.1407358
2012-06-22    1.1619308
2012-06-25    1.1305170
2012-06-26    1.1361939
2012-06-27    1.1418709
2012-06-28    1.1320306
2012-06-29    1.1577674
Name: Adj Close, dtype: float64
2012-07-31 00:00:00
Date
2012-07-02    1.1566316
2012-07-03    1.1642014
2012-07-05    1.1619308
2012-07-06    1.1426280
2012-07-09    1.1354370
2012-07-10    1.1255964
2012-07-11    1.1089432
2012-07-12    1.0835854
2012-07-13    1.1123497
2012-07-16    1.1142420
2012-07-17    1.1225686
2012-07-18    1.1524686
2012-07-19    1.1607951
2012-07-20    1.1399787
2012-07-23    1.1081867
2012-07-24    1.1032663
2012-07-25    1.0911550
2012-07-26    1.1036448
2012-07-27    1.1263534
2012-07-30    1.1218119
2012-07-31    1.1153778
Name: Adj Close, dtype: float64
2012-08-31 00:00:00
Date
2012-08-01    1.1131068
2012-08-02    1.1047803
2012-08-03    1.1259750
2012-08-06    1.1335444
2012-08-07    1.1452771
2012-08-08    1.1479269
2012-08-09    1.1543607
2012-08-10    1.1513331
2012-08-13    1.1501978
2012-08-14    1.1479116
2012-08-15    1.1505788
2012-08-16    1.1726758
2012-08-17    1.1772476
2012-08-20    1.1711520
2012-08-21    1.1734381
2012-08-22    1.1635321
2012-08-23    1.1528645
2012-08-24    1.1642939
2012-08-27    1.1692471
2012-08-28    1.1669613
2012-08-29    1.1677230
2012-08-30    1.1551507
2012-08-31    1.1741999
Name: Adj Close, dtype: float64
2012-09-30 00:00:00
Date
2012-09-04    1.1578177
2012-09-05    1.1578177
2012-09-06    1.1943921
2012-09-07    1.1791524
2012-09-10    1.1703901
2012-09-11    1.1730568
2012-09-12    1.1726758
2012-09-13    1.1787716
2012-09-14    1.1890583
2012-09-17    1.1890583
2012-09-18    1.1879154
2012-09-19    1.1829625
2012-09-20    1.1982021
2012-09-21    1.1882966
2012-09-24    1.1726758
2012-09-25    1.1578177
2012-09-26    1.1494355
2012-09-27    1.1490547
2012-09-28    1.1338153
Name: Adj Close, dtype: float64
2012-10-31 00:00:00
Date
2012-10-01    1.1235283
2012-10-02    1.1300054
2012-10-03    1.1376254
2012-10-04    1.1441018
2012-10-05    1.1372439
2012-10-08    1.1345775
2012-10-09    1.1155281
2012-10-10    1.1040983
2012-10-11    1.1029554
2012-10-12    1.1124800
2012-10-15    1.1242903
2012-10-16    1.1235283
2012-10-17    1.1273384
2012-10-18    1.1239099
2012-10-19    1.0911448
2012-10-22    1.0667618
2012-10-23    1.0686664
2012-10-24    1.0629517
2012-10-25    1.0621899
2012-10-26    1.0747624
2012-10-31    1.0873348
Name: Adj Close, dtype: float64
2012-11-30 00:00:00
Date
2012-11-01    1.1246716
2012-11-02    1.1239099
2012-11-05    1.1288623
2012-11-06    1.1376254
2012-11-07    1.1079079
2012-11-08    1.0976215
2012-11-09    1.0983835
2012-11-12    1.0751436
2012-11-13    1.0405729
2012-11-14    1.0309701
2012-11-15    1.0240558
2012-11-16    1.0186782
2012-11-19    1.0267445
2012-11-20    1.0259766
2012-11-21    1.0351955
2012-11-23    1.0640038
2012-11-26    1.0520962
2012-11-27    1.0401885
2012-11-28    1.0509440
2012-11-29    1.0351955
2012-11-30    1.0225193
Name: Adj Close, dtype: float64
2012-12-31 00:00:00
Date
2012-12-03    1.0152215
2012-12-04    1.0129168
2012-12-05    1.0244400
2012-12-06    1.0267445
2012-12-07    1.0163734
2012-12-10    1.0348109
2012-12-11    1.0494073
2012-12-12    1.0463346
2012-12-13    1.0413410
2012-12-14    1.0298175
2012-12-17    1.0409571
2012-12-18    1.0586262
2012-12-19    1.0490235
2012-12-20    1.0632356
2012-12-21    1.0544012
2012-12-24    1.0394206
2012-12-26    1.0317378
2012-12-27    1.0355794
2012-12-28    1.0198304
2012-12-31    1.0259766
Name: Adj Close, dtype: float64
2013-01-31 00:00:00
Date
2013-01-02    1.0609310
2013-01-03    1.0467187
2013-01-04    1.0271288
2013-01-07    1.0252083
2013-01-08    1.0198304
2013-01-09    1.0255926
2013-01-10    1.0163734
2013-01-11    1.0305858
2013-01-14    1.0328906
2013-01-15    1.0451824
2013-01-16    1.0386524
2013-01-17    1.0467187
2013-01-18    1.0467187
2013-01-22    1.0428778
2013-01-23    1.0605470
2013-01-24    1.0613151
2013-01-25    1.0709179
2013-01-28    1.0720704
2013-01-29    1.0759115
2013-01-30    1.0697658
2013-01-31    1.0544012
Name: Adj Close, dtype: float64
2013-02-28 00:00:00
Date
2013-02-01    1.0728388
2013-02-04    1.0540167
2013-02-05    1.0563217
2013-02-06    1.0501758
2013-02-07    1.0478710
2013-02-08    1.0582422
2013-02-11    1.0701499
2013-02-12    1.0709179
2013-02-13    1.0766800
2013-02-14    1.0770640
2013-02-15    1.0759115
2013-02-19    1.0863686
2013-02-20    1.0793974
2013-02-21    1.0646799
2013-02-22    1.0751366
2013-02-25    1.0600323
2013-02-26    1.0600323
2013-02-27    1.0770733
2013-02-28    1.0766861
Name: Adj Close, dtype: float64
2013-03-31 00:00:00
Date
2013-03-01    1.0824958
2013-03-04    1.0902416
2013-03-05    1.0979876
2013-03-06    1.0879178
2013-03-07    1.0898542
2013-03-08    1.0844323
2013-03-11    1.0793974
2013-03-12    1.0809465
2013-03-13    1.0813338
2013-03-14    1.0898542
2013-03-15    1.0859813
2013-03-18    1.0883052
2013-03-19    1.0914036
2013-03-20    1.0968256
2013-03-21    1.0886925
2013-03-22    1.0941145
2013-03-25    1.0906289
2013-03-26    1.0906289
2013-03-27    1.0987618
2013-03-28    1.1080573
Name: Adj Close, dtype: float64
2013-04-30 00:00:00
Date
2013-04-01    1.1080573
2013-04-02    1.1154158
2013-04-03    1.1061208
2013-04-04    1.1076700
2013-04-05    1.1115431
2013-04-08    1.1072825
2013-04-09    1.1467869
2013-04-10    1.1727359
2013-04-11    1.1208383
2013-04-12    1.1150287
2013-04-15    1.1111557
2013-04-16    1.1219999
2013-04-17    1.1165779
2013-04-18    1.1150287
2013-04-19    1.1529839
2013-04-22    1.1940375
2013-04-23    1.1851294
2013-04-24    1.2300557
2013-04-25    1.2370273
2013-04-26    1.2312179
2013-04-29    1.2629764
2013-04-30    1.2819538
Name: Adj Close, dtype: float64
2013-05-31 00:00:00
Date
2013-05-01    1.2672362
2013-05-02    1.2842774
2013-05-03    1.2970582
2013-05-06    1.3071279
2013-05-07    1.2900869
2013-05-08    1.2776934
2013-05-09    1.2649127
2013-05-10    1.2660745
2013-05-13    1.2792427
2013-05-14    1.3077133
2013-05-15    1.3201938
2013-05-16    1.3291643
2013-05-17    1.3599751
2013-05-20    1.3681658
2013-05-21    1.3591951
2013-05-22    1.3498351
2013-05-23    1.3318944
2013-05-24    1.3365751
2013-05-28    1.3658255
2013-05-29    1.3603651
2013-05-30    1.3662154
2013-05-31    1.3611454
Name: Adj Close, dtype: float64
2013-06-30 00:00:00
Date
2013-06-03    1.3880560
2013-06-04    1.3646559
2013-06-05    1.3564652
2013-06-06    1.3634856
2013-06-07    1.3911764
2013-06-10    1.3833763
2013-06-11    1.3588053
2013-06-12    1.3650460
2013-06-13    1.3541252
2013-06-14    1.3416444
2013-06-17    1.3650460
2013-06-18    1.3642655
2013-06-19    1.3490547
2013-06-20    1.3061534
2013-06-21    1.2975730
2013-06-24    1.3151237
2013-06-25    1.3131739
2013-06-26    1.3396944
2013-06-27    1.3502250
2013-06-28    1.3471047
Name: Adj Close, dtype: float64
2013-07-31 00:00:00
Date
2013-07-01    1.3400849
2013-07-02    1.3237040
2013-07-03    1.3264345
2013-07-05    1.3342343
2013-07-08    1.3389144
2013-07-09    1.3396944
2013-07-10    1.3533451
2013-07-11    1.3919565
2013-07-12    1.3911764
2013-07-15    1.4106771
2013-07-16    1.4145772
2013-07-17    1.3939067
2013-07-18    1.3822060
2013-07-19    1.2246409
2013-07-22    1.2484317
2013-07-23    1.2410213
2013-07-24    1.2464813
2013-07-25    1.2242507
2013-07-26    1.2332212
2013-07-29    1.2301012
2013-07-30    1.2421917
2013-07-31    1.2418012
Name: Adj Close, dtype: float64
2013-08-31 00:00:00
Date
2013-08-01    1.2351713
2013-08-02    1.2437514
2013-08-05    1.2363414
2013-08-06    1.2316609
2013-08-07    1.2503817
2013-08-08    1.2827528
2013-08-09    1.2753425
2013-08-12    1.2819728
2013-08-13    1.2658695
2013-08-14    1.2705826
2013-08-15    1.2485881
2013-08-16    1.2489807
2013-08-19    1.2328772
2013-08-20    1.2419112
2013-08-21    1.2415184
2013-08-22    1.2721538
2013-08-23    1.3648452
2013-08-26    1.3412796
2013-08-27    1.3063237
2013-08-28    1.2968976
2013-08-29    1.3177141
2013-08-30    1.3118223
Name: Adj Close, dtype: float64
2013-09-30 00:00:00
Date
2013-09-03    1.2521225
2013-09-04    1.2254152
2013-09-05    1.2265934
2013-09-06    1.2234514
2013-09-09    1.2434821
2013-09-10    1.2721538
2013-09-11    1.2859005
2013-09-12    1.2839366
2013-09-13    1.2972903
2013-09-16    1.2882568
2013-09-17    1.2933627
2013-09-18    1.3086808
2013-09-19    1.3212490
2013-09-20    1.2878643
2013-09-23    1.2859005
2013-09-24    1.2745104
2013-09-25    1.2768667
2013-09-26    1.2870787
2013-09-27    1.3067167
2013-09-30    1.3071096
Name: Adj Close, dtype: float64
2013-10-31 00:00:00
Date
2013-10-01    1.3188924
2013-10-02    1.3322463
2013-10-03    1.3298892
2013-10-04    1.3306750
2013-10-07    1.3078951
2013-10-08    1.2965049
2013-10-09    1.2988612
2013-10-10    1.3259621
2013-10-11    1.3404942
2013-10-14    1.3530628
2013-10-15    1.3546336
2013-10-16    1.3605250
2013-10-17    1.3715224
2013-10-18    1.3730933
2013-10-21    1.3742713
2013-10-22    1.3581683
2013-10-23    1.3259621
2013-10-24    1.3243910
2013-10-25    1.4033362
2013-10-28    1.3970518
2013-10-29    1.3950879
2013-10-30    1.3958738
2013-10-31    1.3907675
Name: Adj Close, dtype: float64
2013-11-30 00:00:00
Date
2013-11-01    1.3954808
2013-11-04    1.4115837
2013-11-05    1.4390769
2013-11-06    1.4995625
2013-11-07    1.4728544
2013-11-08    1.4838517
2013-11-11    1.4763897
2013-11-12    1.4673562
2013-11-13    1.4987771
2013-11-14    1.4932780
2013-11-15    1.4862091
2013-11-18    1.4610717
2013-11-19    1.4539484
2013-11-20    1.4674033
2013-11-21    1.4800677
2013-11-22    1.4867954
2013-11-25    1.4895651
2013-11-26    1.4780884
2013-11-27    1.4879820
2013-11-29    1.5089562
Name: Adj Close, dtype: float64
2013-12-31 00:00:00
Date
2013-12-02    1.5216200
2013-12-03    1.5160798
2013-12-04    1.5410111
2013-12-05    1.5038117
2013-12-06    1.5180585
2013-12-09    1.5319094
2013-12-10    1.5081650
2013-12-11    1.4883780
2013-12-12    1.4729441
2013-12-13    1.4519700
2013-12-16    1.4598846
2013-12-17    1.4452423
2013-12-18    1.4476167
2013-12-19    1.4345570
2013-12-20    1.4563228
2013-12-23    1.4491996
2013-12-24    1.4674033
2013-12-26    1.4816502
2013-12-27    1.4757146
2013-12-30    1.4757146
Name: Adj Close, dtype: float64

In [39]:
len(msft_monthly_cum_ret)
# 24 groups confirmed.

24

In [40]:
msft_monthly_cum_ret.size()
# size of each group.

Date
2012-01-31    20
2012-02-29    20
2012-03-31    22
2012-04-30    20
2012-05-31    22
2012-06-30    21
2012-07-31    21
2012-08-31    23
2012-09-30    19
2012-10-31    21
2012-11-30    21
2012-12-31    20
2013-01-31    21
2013-02-28    19
2013-03-31    20
2013-04-30    22
2013-05-31    22
2013-06-30    20
2013-07-31    22
2013-08-31    22
2013-09-30    20
2013-10-31    23
2013-11-30    20
2013-12-31    20
Freq: M, Name: Adj Close, dtype: int64

In [41]:
msft_monthly_cum_ret.mean()

Date
2012-01-31    1.0686748
2012-02-29    1.1556977
2012-03-31    1.2105697
2012-04-30    1.1846437
2012-05-31    1.1405161
2012-06-30    1.1233437
2012-07-31    1.1262454
2012-08-31    1.1536295
2012-09-30    1.1727561
2012-10-31    1.1073820
2012-11-30    1.0648222
2012-12-31    1.0358098
2013-01-31    1.0462066
2013-02-28    1.0678735
2013-03-31    1.0898930
2013-04-30    1.1568920
2013-05-31    1.3204533
2013-06-30    1.3507125
2013-07-31    1.3124115
2013-08-31    1.2726700
2013-09-30    1.2773971
2013-10-31    1.3503986
2013-11-30    1.4719149
2013-12-31    1.4823627
Freq: M, Name: Adj Close, dtype: float64

In [42]:
msft_cum_ret['2/2012'].mean()
# to compare and confirm the mean of feb in immediately above series. Confirmed and the same.

1.1556976828189458

In [43]:
## The above work is almost the end of page 94 in the book. After that, for about 3 pages, the discussion in the book cannot be
# implemented here since there is change in the newer version of pandas. But what we can do something extra and interesting follows
# as:

In [44]:
msft

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6231327
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1320133
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.3581753
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7055073
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4066410
...,...,...,...,...,...,...
2013-12-23,36.8899994,36.5499992,36.8100014,36.6199989,25128700.0,31.3362350
2013-12-24,37.1699982,36.6399994,36.7200012,37.0800018,14243000.0,31.7298565
2013-12-26,37.4900017,37.1699982,37.2000008,37.4399986,17612800.0,32.0379181
2013-12-27,37.6199989,37.1699982,37.5800018,37.2900009,14563000.0,31.9095726
2013-12-30,37.3800011,36.9000015,37.2200012,37.2900009,16290500.0,31.9095726

In [45]:
msft_resample = msft.resample('M')
# the frequency has been changed to Monthly from Daily.

In [46]:
msft_resample

In [47]:
for i, k in msft_resample:
    print(i)
    print(k)
# the data has been grouped on monthly basis into 24 groups since we have 24 months.

2012-01-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-01-03  26.9599991  26.3899994  26.5499992  26.7700005   64731500.0
2012-01-04  27.4699993  26.7800007  26.8199997  27.3999996   80516100.0
2012-01-05  27.7299995  27.2900009  27.3799992  27.6800003   56081400.0
2012-01-06  28.1900005  27.5300007  27.5300007  28.1100006   99455500.0
2012-01-09  28.1000004  27.7199993  28.0499992  27.7399998   59706800.0
2012-01-10  28.1499996  27.7500000  27.9300003  27.8400002   60014400.0
2012-01-11  27.9799995  27.3700008  27.4300003  27.7199993   65582400.0
2012-01-12  28.0200005  27.6499996  27.8700008  28.0000000   49370800.0
2012-01-13  28.2500000  27.7900009  27.9300003  28.2500000   60196100.0
2012-01-17  28.6499996  28.1700001  28.3999996  28.2600002   72395300.0
2012-01-18  28.3999996  27.9699993  28.3099995  28.2299995   64860600.0
2012-01-19  28.4400005  28.0300007  28.1599998  28.1200008   74053500.0
2012-01-20  29.7399998  28.7500000  28.8199997  29.7099991  165902900.0
2012-01-23  29.9500008  29.3500004  29.5499992  29.7299995   76078100.0
2012-01-24  29.5699997  29.1800003  29.4699993  29.3400002   51703300.0
2012-01-25  29.6499996  29.0699997  29.0699997  29.5599995   59231700.0
2012-01-26  29.7000008  29.3999996  29.6100006  29.5000000   49102800.0
2012-01-27  29.5300007  29.1700001  29.4500008  29.2299995   44187700.0
2012-01-30  29.6200008  28.8299999  28.9699993  29.6100006   51114800.0
2012-01-31  29.7000008  29.2299995  29.6599998  29.5300007   50572400.0

             Adj Close
Date
2012-01-03  21.6231327
2012-01-04  22.1320133
2012-01-05  22.3581753
2012-01-06  22.7055073
2012-01-09  22.4066410
2012-01-10  22.4874115
2012-01-11  22.3904819
2012-01-12  22.6166534
2012-01-13  22.8185863
2012-01-17  22.8266640
2012-01-18  22.8024311
2012-01-19  22.7135811
2012-01-20  23.9978809
2012-01-23  24.0140400
2012-01-24  23.6990223
2012-01-25  23.8767204
2012-01-26  23.8282623
2012-01-27  23.6101665
2012-01-30  23.9171085
2012-01-31  23.8524876
2012-02-29 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-02-01  30.0499992  29.7600002  29.7900009  29.8899994  67409900.0
2012-02-02  30.1700001  29.7099991  29.8999996  29.9500008  52223300.0
2012-02-03  30.3999996  30.0900002  30.1399994  30.2399998  41838500.0
2012-02-06  30.2199993  29.9699993  30.0400009  30.2000008  28039700.0
2012-02-07  30.4899998  30.0499992  30.1499996  30.3500004  39242400.0
2012-02-08  30.6700001  30.2199993  30.2600002  30.6599998  49659100.0
2012-02-09  30.7999992  30.4799995  30.6800003  30.7700005  50481600.0
2012-02-10  30.7999992  30.3600006  30.6399994  30.5000000  44605300.0
2012-02-13  30.7700005  30.4300003  30.6299992  30.5799999  33319800.0
2012-02-14  30.4599991  29.8500004  30.3299999  30.2500000  59644000.0
2012-02-15  30.3899994  30.0300007  30.3299999  30.0499992  43311300.0
2012-02-16  31.5499992  30.2999992  30.3099995  31.2900009  94705100.0
2012-02-17  31.3199997  30.9500008  31.2000008  31.2500000  70036500.0
2012-02-21  31.6100006  31.1499996  31.1800003  31.4400005  50829900.0
2012-02-22  31.6800003  31.1800003  31.4500008  31.2700005  49253200.0
2012-02-23  31.5900002  31.0000000  31.2000008  31.3700008  35034700.0
2012-02-24  31.5000000  31.2399998  31.4799995  31.4799995  35575400.0
2012-02-27  31.5000000  31.1000004  31.2399998  31.3500004  34568400.0
2012-02-28  31.9300003  31.3799992  31.4099998  31.8700008  45230600.0
2012-02-29  32.0000000  31.6100006  31.8899994  31.7399998  59323600.0

             Adj Close
Date
2012-02-01  24.1432743
2012-02-02  24.1917419
2012-02-03  24.4259892
2012-02-06  24.3936768
2012-02-07  24.5148354
2012-02-08  24.7652321
2012-02-09  24.8540897
2012-02-10  24.6359959
2012-02-13  24.7006187
2012-02-14  24.5949211
2012-02-15  24.4323101
2012-02-16  25.4405003
2012-02-17  25.4079742
2012-02-21  25.5624542
2012-02-22  25.4242363
2012-02-23  25.5055389
2012-02-24  25.5949745
2012-02-27  25.4892788
2012-02-28  25.9120731
2012-02-29  25.8063717
2012-03-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-03-01  32.3899994  31.8500004  31.9300003  32.2900009  77344100.0
2012-03-02  32.4399986  32.0000000  32.3100014  32.0800018  47314200.0
2012-03-05  32.0499992  31.6200008  32.0099983  31.7999992  45240000.0
2012-03-06  31.9799995  31.4899998  31.5400009  31.5599995  51932900.0
2012-03-07  31.9200001  31.5300007  31.6700001  31.8400002  34340400.0
2012-03-08  32.2099991  31.8999996  32.0400009  32.0099983  36747400.0
2012-03-09  32.1599998  31.9200001  32.0999985  31.9899998  34628400.0
2012-03-12  32.2000008  31.8199997  31.9699993  32.0400009  34073600.0
2012-03-13  32.6899986  32.1500015  32.2400017  32.6699982  48951700.0
2012-03-14  32.8800011  32.4900017  32.5299988  32.7700005  41986900.0
2012-03-15  32.9399986  32.5800018  32.7900009  32.8499985  49068300.0
2012-03-16  32.9500008  32.5000000  32.9099998  32.5999985  65626400.0
2012-03-19  32.6100006  32.1500015  32.5400009  32.2000008  44789200.0
2012-03-20  32.1500015  31.7399998  32.0999985  31.9899998  41566800.0
2012-03-21  32.1500015  31.8199997  31.9599991  31.9099998  37928600.0
2012-03-22  32.0900002  31.7900009  31.8099995  32.0000000  31749500.0
2012-03-23  32.1100006  31.7199993  32.0999985  32.0099983  35912200.0
2012-03-26  32.6100006  32.1500015  32.1899986  32.5900002  36758300.0
2012-03-27  32.7000008  32.4000015  32.6500015  32.5200005  36274900.0
2012-03-28  32.7000008  32.0400009  32.5200005  32.1899986  41344800.0
2012-03-29  32.1899986  31.8099995  32.0600014  32.1199989  37038500.0
2012-03-30  32.4099998  32.0400009  32.4000015  32.2599983  31749400.0

             Adj Close
Date
2012-03-01  26.2535439
2012-03-02  26.0828094
2012-03-05  25.8551502
2012-03-06  25.6600189
2012-03-07  25.8876781
2012-03-08  26.0258961
2012-03-09  26.0096321
2012-03-12  26.0502911
2012-03-13  26.5625153
2012-03-14  26.6438236
2012-03-15  26.7088604
2012-03-16  26.5055904
2012-03-19  26.1803761
2012-03-20  26.0096321
2012-03-21  25.9445896
2012-03-22  26.0177631
2012-03-23  26.0258961
2012-03-26  26.4974709
2012-03-27  26.4405479
2012-03-28  26.1722469
2012-03-29  26.1153316
2012-03-30  26.2291603
2012-04-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-04-02  32.4599991  31.9500008  32.2200012  32.2900009   35853600.0
2012-04-03  32.1899986  31.6599998  32.1599998  31.9400005   42752100.0
2012-04-04  31.6900005  31.0499992  31.6599998  31.2099991   49455900.0
2012-04-05  31.6299992  31.0499992  31.1499996  31.5200005   50368600.0
2012-04-09  31.3999996  30.9699993  31.2199993  31.1000004   31056400.0
2012-04-10  31.1900005  30.2999992  31.0599995  30.4699993   54131300.0
2012-04-11  30.5300007  30.2299995  30.4300003  30.3500004   43014000.0
2012-04-12  31.0400009  30.4200001  30.4799995  30.9799995   38304000.0
2012-04-13  31.1599998  30.7199993  30.8899994  30.8099995   39749200.0
2012-04-16  31.1900005  30.7700005  30.9899998  31.0799999   38124800.0
2012-04-17  31.6100006  31.2000008  31.2700005  31.4400005   34361500.0
2012-04-18  31.3099995  31.0400009  31.2800007  31.1399994   40552900.0
2012-04-19  31.6800003  30.9400005  31.1299992  31.0100002   54781200.0
2012-04-20  32.8899994  32.0499992  32.1500015  32.4199982  106045000.0
2012-04-23  32.5000000  32.0299988  32.3100014  32.1199989   61398200.0
2012-04-24  32.5200005  31.8299999  32.2099991  31.9200001   40871100.0
2012-04-25  32.3199997  31.8700008  31.9200001  32.2000008   62495500.0
2012-04-26  32.2299995  31.9200001  32.1199989  32.1100006   40308100.0
2012-04-27  32.2200012  31.8799992  32.1199989  31.9799995   41419100.0
2012-04-30  32.1100006  31.9200001  31.9799995  32.0200005   35697200.0

             Adj Close
Date
2012-04-02  26.2535439
2012-04-03  25.9689770
2012-04-04  25.3754520
2012-04-05  25.6274986
2012-04-09  25.2860146
2012-04-10  24.7737923
2012-04-11  24.6762218
2012-04-12  25.1884422
2012-04-13  25.0502300
2012-04-16  25.2697544
2012-04-17  25.5624542
2012-04-18  25.3185310
2012-04-19  25.2128372
2012-04-20  26.3592472
2012-04-23  26.1153316
2012-04-24  25.9527187
2012-04-25  26.1803761
2012-04-26  26.1072025
2012-04-27  26.0014992
2012-04-30  26.0340233
2012-05-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-05-01  32.3400002  31.9500008  32.0499992  32.0099983  43832300.0
2012-05-02  31.9300003  31.6399994  31.8500004  31.7999992  37385300.0
2012-05-03  31.8999996  31.6100006  31.8799992  31.7600002  31501300.0
2012-05-04  31.5699997  30.9200001  31.4500008  30.9799995  57927200.0
2012-05-07  30.8600006  30.5699997  30.7000008  30.6499996  48641400.0
2012-05-08  30.7800007  30.1700001  30.4799995  30.5000000  46328300.0
2012-05-09  30.8299999  30.1000004  30.1900005  30.7600002  50309300.0
2012-05-10  31.0200005  30.4500008  30.8600006  30.7399998  43839200.0
2012-05-11  31.5400009  30.6900005  30.6900005  31.1599998  43459300.0
2012-05-14  31.0400009  30.6399994  30.8199997  30.6800003  40528900.0
2012-05-15  30.7999992  30.1499996  30.6399994  30.2099991  61822800.0
2012-05-16  30.3199997  29.7399998  30.3099995  29.8999996  60083700.0
2012-05-17  30.2099991  29.7099991  29.9899998  29.7199993  48484000.0
2012-05-18  29.8099995  29.1700001  29.7900009  29.2700005  56205300.0
2012-05-21  29.7900009  29.0599995  29.1000004  29.7500000  38787900.0
2012-05-22  29.8799992  29.5000000  29.6900005  29.7600002  39504900.0
2012-05-23  29.3999996  28.6399994  29.3500004  29.1100006  65171000.0
2012-05-24  29.2999992  28.7600002  29.1599998  29.0699997  52575000.0
2012-05-25  29.3600006  29.0100002  29.2000008  29.0599995  29507200.0
2012-05-29  29.7199993  29.2199993  29.3799992  29.5599995  37758800.0
2012-05-30  29.4799995  29.1200008  29.3500004  29.3400002  41585500.0
2012-05-31  29.4200001  28.9400005  29.2999992  29.1900005  39134000.0

             Adj Close
Date
2012-05-01  26.0258961
2012-05-02  25.8551502
2012-05-03  25.8226318
2012-05-04  25.1884422
2012-05-07  24.9201393
2012-05-08  24.7981777
2012-05-09  25.0095768
2012-05-10  24.9933167
2012-05-11  25.3347988
2012-05-14  24.9445343
2012-05-15  24.7235641
2012-05-16  24.4698639
2012-05-17  24.3225594
2012-05-18  23.9542828
2012-05-21  24.3471069
2012-05-22  24.3552895
2012-05-23  23.8233395
2012-05-24  23.7906036
2012-05-25  23.7824135
2012-05-29  24.1916065
2012-05-30  24.0115700
2012-05-31  23.8888111
2012-06-30 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-06-01  28.9599991  28.4400005  28.7600002  28.4500008  56634300.0
2012-06-04  28.7800007  28.3199997  28.6200008  28.5499992  47926300.0
2012-06-05  28.7500000  28.3899994  28.5100002  28.5100002  45715400.0
2012-06-06  29.3700008  28.8099995  28.8799992  29.3500004  46860500.0
2012-06-07  29.7000008  29.1700001  29.6399994  29.2299995  37792800.0
2012-06-08  29.6800003  29.0499992  29.2099991  29.6499996  42551100.0
2012-06-11  29.8099995  28.8199997  29.7299995  28.8999996  46361900.0
2012-06-12  29.2999992  28.8400002  29.1000004  29.2900009  35337900.0
2012-06-13  29.4400005  29.0499992  29.2199993  29.1299992  32984600.0
2012-06-14  29.4599991  28.8799992  29.3299999  29.3400002  39458900.0
2012-06-15  30.0799999  29.4899998  29.5900002  30.0200005  62314400.0
2012-06-18  30.0300007  29.7099991  29.9899998  29.8400002  58679900.0
2012-06-19  31.1100006  30.0499992  30.1900005  30.7000008  75725800.0
2012-06-20  31.0499992  30.6399994  30.9300003  30.9300003  36257100.0
2012-06-21  31.1399994  30.0599995  30.9599991  30.1399994  48456600.0
2012-06-22  30.7299995  30.0300007  30.2999992  30.7000008  45098100.0
2012-06-25  30.3199997  29.6200008  30.2999992  29.8700008  42217200.0
2012-06-26  30.2700005  29.9400005  30.0000000  30.0200005  38421300.0
2012-06-27  30.5000000  30.0300007  30.1900005  30.1700001  33781700.0
2012-06-28  30.0499992  29.4200001  29.9799995  29.9099998  45328400.0
2012-06-29  30.6900005  30.1399994  30.4500008  30.5900002  55227200.0

             Adj Close
Date
2012-06-01  23.2832031
2012-06-04  23.3650436
2012-06-05  23.3323059
2012-06-06  24.0197487
2012-06-07  23.9215355
2012-06-08  24.2652721
2012-06-11  23.6514740
2012-06-12  23.9706478
2012-06-13  23.8396950
2012-06-14  24.0115700
2012-06-15  24.5680714
2012-06-18  24.4207611
2012-06-19  25.1245842
2012-06-20  25.3128090
2012-06-21  24.6662827
2012-06-22  25.1245842
2012-06-25  24.4453201
2012-06-26  24.5680714
2012-06-27  24.6908264
2012-06-28  24.4780483
2012-06-29  25.0345573
2012-07-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-07-02  30.6200008  30.2099991  30.6200008  30.5599995  30589100.0
2012-07-03  30.7600002  30.1700001  30.2299995  30.7600002  20938100.0
2012-07-05  30.7800007  30.3799992  30.5900002  30.7000008  28801900.0
2012-07-06  30.7000008  29.9500008  30.6100006  30.1900005  38294800.0
2012-07-09  30.2299995  29.7800007  30.1200008  30.0000000  30680800.0
2012-07-10  30.2199993  29.5100002  30.0799999  29.7399998  37534100.0
2012-07-11  29.7399998  29.1100006  29.7099991  29.2999992  39184900.0
2012-07-12  29.1800003  28.5400009  29.1499996  28.6299992  63523600.0
2012-07-13  29.4799995  28.7199993  28.7600002  29.3899994  39085000.0
2012-07-16  29.5300007  29.0400009  29.4799995  29.4400005  27900600.0
2012-07-17  29.8600006  29.2000008  29.6399994  29.6599998  33771300.0
2012-07-18  30.4500008  29.4599991  29.6000004  30.4500008  41090400.0
2012-07-19  30.7999992  30.3799992  30.5100002  30.6700001  46663200.0
2012-07-20  31.0499992  30.0499992  31.0000000  30.1200008  64021700.0
2012-07-23  29.5799999  29.0100002  29.5699997  29.2800007  55151900.0
2012-07-24  29.3600006  28.8999996  29.2399998  29.1499996  47723300.0
2012-07-25  29.3299999  28.7800007  29.2399998  28.8299999  45579500.0
2012-07-26  29.5000000  29.0900002  29.2299995  29.1599998  45301400.0
2012-07-27  29.8500004  29.1800003  29.4799995  29.7600002  44242600.0
2012-07-30  29.8199997  29.4599991  29.7500000  29.6399994  28905000.0
2012-07-31  29.7099991  29.3299999  29.4799995  29.4699993  37620900.0

             Adj Close
Date
2012-07-02  25.0099983
2012-07-03  25.1736813
2012-07-05  25.1245842
2012-07-06  24.7071972
2012-07-09  24.5517044
2012-07-10  24.3389206
2012-07-11  23.9788265
2012-07-12  23.4305115
2012-07-13  24.0524845
2012-07-16  24.0934029
2012-07-17  24.2734509
2012-07-18  24.9199810
2012-07-19  25.1000271
2012-07-20  24.6499100
2012-07-23  23.9624672
2012-07-24  23.8560734
2012-07-25  23.5941887
2012-07-26  23.8642578
2012-07-27  24.3552895
2012-07-30  24.2570877
2012-07-31  24.1179619
2012-08-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-08-01  29.6499996  29.2099991  29.5900002  29.4099998  31721800.0
2012-08-02  29.5300007  28.9699993  29.2099991  29.1900005  39520500.0
2012-08-03  29.9400005  29.4799995  29.5300007  29.7500000  35859400.0
2012-08-06  30.1100006  29.8099995  30.0000000  29.9500008  27471800.0
2012-08-07  30.3500004  29.8700008  30.0699997  30.2600002  28002900.0
2012-08-08  30.4699993  30.1100006  30.2099991  30.3299999  26257600.0
2012-08-09  30.6499996  30.2999992  30.3899994  30.5000000  24920800.0
2012-08-10  30.6200008  30.2500000  30.5000000  30.4200001  27810300.0
2012-08-13  30.4599991  30.1599998  30.3500004  30.3899994  23049100.0
2012-08-14  30.3899994  30.0100002  30.2999992  30.1299992  34551400.0
2012-08-15  30.2800007  30.0200005  30.1100006  30.2000008  24351000.0
2012-08-16  30.9400005  30.2600002  30.3600006  30.7800007  35787200.0
2012-08-17  30.9200001  30.5900002  30.9200001  30.8999996  32589900.0
2012-08-20  30.8500004  30.5799999  30.8199997  30.7399998  23737700.0
2012-08-21  30.9599991  30.6100006  30.7600002  30.7999992  28822700.0
2012-08-22  30.7600002  30.4699993  30.5900002  30.5400009  33437400.0
2012-08-23  30.3999996  30.0799999  30.3899994  30.2600002  28355600.0
2012-08-24  30.6299992  30.1800003  30.2500000  30.5599995  22943300.0
2012-08-27  30.9599991  30.5900002  30.9300003  30.6900005  34691100.0
2012-08-28  30.7999992  30.5200005  30.7000008  30.6299992  23947900.0
2012-08-29  30.7500000  30.4400005  30.6499996  30.6499996  23346800.0
2012-08-30  30.6100006  30.2199993  30.5300007  30.3199997  23982100.0
2012-08-31  30.9599991  30.3799992  30.6000004  30.8199997  36590100.0

             Adj Close
Date
2012-08-01  24.0688553
2012-08-02  23.8888111
2012-08-03  24.3471069
2012-08-06  24.5107803
2012-08-07  24.7644787
2012-08-08  24.8217754
2012-08-09  24.9608955
2012-08-10  24.8954277
2012-08-13  24.8708801
2012-08-14  24.8214455
2012-08-15  24.8791180
2012-08-16  25.3569241
2012-08-17  25.4557819
2012-08-20  25.3239746
2012-08-21  25.3734074
2012-08-22  25.1592083
2012-08-23  24.9285412
2012-08-24  25.1756821
2012-08-27  25.2827854
2012-08-28  25.2333584
2012-08-29  25.2498283
2012-08-30  24.9779778
2012-08-31  25.3898792
2012-09-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-09-04  30.6599998  30.1499996  30.4500008  30.3899994   48556700.0
2012-09-05  30.5300007  30.2099991  30.2199993  30.3899994   33650000.0
2012-09-06  31.3600006  30.4599991  30.5000000  31.3500004   48371700.0
2012-09-07  31.0699997  30.7299995  31.0400009  30.9500008   42649100.0
2012-09-10  30.8999996  30.5100002  30.8299999  30.7199993   40524000.0
2012-09-11  30.9099998  30.6100006  30.6900005  30.7900009   25191800.0
2012-09-12  31.1800003  30.7299995  30.9400005  30.7800007   32775800.0
2012-09-13  31.1800003  30.3999996  30.8899994  30.9400005   45047300.0
2012-09-14  31.2500000  30.8099995  31.0100002  31.2099991   51422800.0
2012-09-17  31.2600002  31.0400009  31.1900005  31.2099991   36488500.0
2012-09-18  31.2099991  31.0300007  31.1000004  31.1800003   34542700.0
2012-09-19  31.1900005  31.0400009  31.0900002  31.0499992   48871900.0
2012-09-20  31.4799995  30.9099998  30.9500008  31.4500008   45543000.0
2012-09-21  31.6100006  31.0900002  31.4300003  31.1900005  102348900.0
2012-09-24  31.0699997  30.6399994  31.0000000  30.7800007   46825900.0
2012-09-25  31.0000000  30.3600006  30.9500008  30.3899994   54266400.0
2012-09-26  30.6000004  30.0400009  30.2800007  30.1700001   54672000.0
2012-09-27  30.3999996  29.8899994  30.1700001  30.1599998   47129900.0
2012-09-28  30.2600002  29.7399998  30.1800003  29.7600002   54229300.0

             Adj Close
Date
2012-09-04  25.0356464
2012-09-05  25.0356464
2012-09-06  25.8264980
2012-09-07  25.4969692
2012-09-10  25.3075008
2012-09-11  25.3651619
2012-09-12  25.3569241
2012-09-13  25.4887352
2012-09-14  25.7111664
2012-09-17  25.7111664
2012-09-18  25.6864529
2012-09-19  25.5793552
2012-09-20  25.9088821
2012-09-21  25.6946945
2012-09-24  25.3569241
2012-09-25  25.0356464
2012-09-26  24.8543968
2012-09-27  24.8461628
2012-09-28  24.5166378
2012-10-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-10-01  29.9799995  29.4200001  29.8099995  29.4899998  54042700.0
2012-10-02  29.8899994  29.5000000  29.6800003  29.6599998  43338900.0
2012-10-03  29.9899998  29.6700001  29.7500000  29.8600006  46655900.0
2012-10-04  30.0300007  29.5699997  29.9699993  30.0300007  43634900.0
2012-10-05  30.2500000  29.7399998  30.2299995  29.8500004  41133900.0
2012-10-08  29.9200001  29.5499992  29.6399994  29.7800007  29752000.0
2012-10-09  29.7399998  29.1800003  29.6800003  29.2800007  45121100.0
2012-10-10  29.3099995  28.9500008  29.1499996  28.9799995  47227100.0
2012-10-11  29.2500000  28.8700008  29.2199993  28.9500008  41488500.0
2012-10-12  29.3199997  28.7999992  28.9699993  29.2000008  46464700.0
2012-10-15  29.7199993  29.2500000  29.3700008  29.5100002  42440200.0
2012-10-16  29.7399998  29.3199997  29.4500008  29.4899998  47739400.0
2012-10-17  29.6399994  29.0900002  29.2999992  29.5900002  44206100.0
2012-10-18  29.7299995  29.2600002  29.6499996  29.5000000  59238500.0

In [48]:
msft_resample.mean().head(3)
# mean of high, low, open, close, volume and adj close for each month.

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-31,28.6900001,28.1710001,28.3479999,28.5165000,6.7742905e+07,23.0338484
2012-02-29,30.9949998,30.5429999,30.7125000,30.8250002,4.9216615e+07,24.9898044
2012-03-31,32.3877273,31.9777278,32.1986364,32.1949996,4.2834841e+07,26.1763102

In [49]:
msft.loc['1/2012', 'Adj Close'].mean()
# confirmed that 'msft_resample.mean()' has produced mean of high, low, open, close, volume and adj close for each month.

23.033848381042482